version: '#{build}'
branches:
  only:
  - master
  - ci
skip_tags: true
clone_depth: 1
build_script:
  - mkdir Build
  - cd Build
  - cmake -G "Visual Studio 12 Win64" -DCMAKE_PREFIX_PATH=C:\Qt\5.7\msvc2013_64\lib\cmake ..
  - cmake --build .
test: off
